# Generated by Django 5.0.3 on 2024-03-08 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.counselor')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('sendby', models.CharField(max_length=20)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.counselor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('report', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='prediction')),
                ('status', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depApp.tests')),
            ],
        ),
    ]
