# Generated by Django 4.2.7 on 2024-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depApp', '0005_remove_consultation_tests_consultation_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
